# change source and destination folders for building site
source: ./jekyll_source
destination: ./jekyll_result

# TODO - FIX THIS, NOT WORKING
# set up default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"