# source and destination folders for jekyll building
source: ./jekyll_source
destination: ./jekyll_result

# sass options
sass:
    style: :compressed # output style
    load_paths: # load paths
        - jekyll_source/_sass
        - jekyll_source/_third_party

# collections
collections:
    collection_web: # web projects
        output: true # generate separate files
    collection_offline: # offline projects
        output: true # generate separate files
    collection_lists: # listing pages for web and offline projects
        output: true # generate separate files

# set up default layouts and permalink
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            permalink: "/lego/:year-:month-:day/:title/"
    -
        scope:
            path: ""
            type: "collection_offline"
        values:
            layout: "offline_project"